#!/bin/sh

rpm --import http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
yum install -y http://yum.puppetlabs.com/el/6/products/x86_64/puppetlabs-release-6-7.noarch.rpm
yum makecache
yum -y install puppet --disableplugin=priorities && yum update -y
